const cartTypes = {
  ADD_ITEM: 'ADD_ITEM',
  DELETE_ITEM: 'DELETE_ITEM',
  CLEAR_ITEM_CART: 'CLEAR_ITEM_CART',
  CLEAR_CART: 'CLEAR_CART',
  TOGGLE_DROPDOWN: 'TOGGLE_DROPDOWN',

  LOAD_CART_FROM_LS: 'LOAD_CART_FROM_LS',
  SAVE_ITEM_TO_CART_LS: 'SAVE_ITEM_TO_CART_LS'
};

export default cartTypes;
