const MainTypes = {
  // // GET_MAIN_DATA: 'GET_MAIN_DATA',
  FETCH_MAIN_DATA_START: 'FETCH_MAIN_DATA_START',
  FETCH_MAIN_DATA_FAILURE: 'FETCH_MAIN_DATA_FAILURE',
  FETCH_MAIN_DATA_SUCCESS: 'FETCH_MAIN_DATA_SUCCESS',
  CLEAR_DATA: 'CLEAR_DATA'
};

export default MainTypes;
