const MainTypes = {
    // // GET_MAIN_DATA: 'GET_MAIN_DATA',
    FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
    FETCH_COLLECTION_FAILURE: 'FETCH_COLLECTION_FAILURE',
    FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
    CLEAR_DATA: 'CLEAR_DATA',
}

export default MainTypes;