const userTypes = {
  // SET CURRENT USER
  SET_CURRENT_USER_START: 'SET_CURRENT_USER_START',
  SET_CURRENT_USER_SUCCESS: 'SET_CURRENT_USER_SUCCESS',
  SET_CURRENT_USER_FAILURE: 'SET_CURRENT_USER_FAILURE',

  // LOGIN
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  // REGISTER
  REGISTER_START: 'REGISTER_START',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  REGISTER_FAILURE: 'REGISTER_FAILURE',

  // LOGOUT
  LOG_OUT_START: 'LOG_OUT_START',
  LOG_OUT_SUCCESS: 'LOG_OUT_SUCCESS',
  LOG_OUT_FAILURE: 'LOG_OUT_FAILURE'
};

export default userTypes;
