const ProductTypes = {
  FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCT_FAILURE: 'FETCH_PRODUCT_FAILURE',
  CLEAR_PRODUCT: 'CLEAR_PRODUCT'
};

export default ProductTypes;
